import type { Metadata } from "next";
import MainNavigation from "@/components/auth/mainNagivation";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { Toaster } from "sonner";
import "./globals.css";
import AuthNavigation from "@/components/auth/authNavigation";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Thebob",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const cookiePromise = await cookies();
  // console.log(cookiePromise.get("GUID"))

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Sarabun:wght@100;200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className} antialiased`}>
        <Toaster richColors position="top-center" />
        <Providers>
          {
            cookiePromise.get("GUID")?.value
              ? <MainNavigation>{children}</MainNavigation>
              : <AuthNavigation>{children}</AuthNavigation>
          }
        </Providers>
      </body>
    </html>
  );
}
